app/jobs/routes.py
from app import db
from flask import render_template, redirect, url_for, flash, request, Blueprint
from flask_login import current_user, login_user, logout_user, login_required
from werkzeug.urls import url_parse
from datetime import datetime

from app.jobs.forms import EmployerPostForm, SeekerPostForm, SearchForm, FeedbackForm, MessageForm
from app.models import User, Job, Works, Message


jobs = Blueprint('jobs', __name__)


@jobs.route('/job_post', methods=['GET', 'POST'])
@login_required
def job_post():
    eform = EmployerPostForm()
    sform = SeekerPostForm()
    post = Job()
    if sform.validate_on_submit():
        post.title = sform.stitle.data
        post.description = sform.sdescription.data
        post.jobType = sform.sjob_type.data
        post.location = sform.slocation.data
        post.salary = sform.ssalary.data
        post.user = current_user
        post.postType = 'Seeker'
        db.session.add(post)
        db.session.commit()
        flash('Successfully posted job seeker!', category='success')
        return redirect(url_for('users.home', username=current_user.username, post_page=1, hired_page=1, history_page=1))
    if eform.validate_on_submit():
        post.title = eform.title.data
        post.postType = 'Employer'
        post.description = eform.description.data
        post.jobType = eform.job_type.data
        post.location = eform.location.data
        post.salary = eform.salary.data
        post.maxWorker = eform.maxWorker.data
        post.user = current_user
        db.session.add(post)
        db.session.commit()
        flash('Successfully posted job employer!', category='success')
        return redirect(url_for('users.home', username=current_user.username, post_page=1, hired_page=1, history_page=1))
    else:
        return render_template('job_post.html', title='Job Post', eform=eform, sform=sform)


@jobs.route('/edit_job/<id>', methods=['GET', 'POST'])
@login_required
def edit_job(id):
    job = Job().query.filter_by(id=id).first()
    form = EmployerPostForm()
    if form.validate_on_submit():
        if form.maxWorker.data:
            job.maxWorker = form.maxWorker.data
        job.title = form.title.data
        job.description = form.description.data
        job.jobType = form.job_type.data
        job.location = form.location.data
        job.salary = form.salary.data
        db.session.commit()
        flash('Successfully Edited Job', category='success')
        return redirect(url_for('users.home', username=current_user.username, post_page=1, hired_page=1, history_page=1))
    else:
        if job.maxWorker is not None:
            form.maxWorker.data = job.maxWorker
        form.title.data = job.title
        form.description.data = job.description
        form.job_type.data = job.jobType
        form.location.data = job.location
        form.salary.data = job.salary
        return render_template('edit_job.html', form=form, title='Edit Job')


@jobs.route('/delete_job/<id>')
def delete_job(id):
    job = Job.query.filter_by(id=id).first()
    w = Works.query.filter(Works.jobID == job.id)
    for work in w:
        if work.status == 'Working':
            work.worker.isEmployed = False
            db.session.delete(work)
        if work.status == 'Hiring':
            j = Job.query.filter(Job.id == work.jobID).first()
            j.user.isEmployed = False
            db.session.delete(work)
    db.session.delete(job)
    db.session.commit()
    flash('Successfully Deleted Job', category='success')
    return redirect(url_for('users.home', username=current_user.username, post_page=1, hired_page=1, history_page=1))


@jobs.route('/job_search/<page>', methods=['GET', 'POST'])
def job_search(page):
    search = SearchForm()
    if search.validate_on_submit():
        return redirect(url_for('jobs.search_result', category=search.category.data, search=search.search.data, page=page))
        # return render_template('job_search.html', title='Search Result', sform=search, jobs=jobs)
    else:
        jobs = Job.query.order_by(
            Job.timeStamp.desc()).paginate(per_page=2, page=int(page))
        return render_template('job_search.html', title='Job Search', sform=search, jobs=jobs, check=True, search=False)


@jobs.route('/job_search/<category>/<search>/<page>', methods=['GET', 'POST'])
def search_result(category, search, page):
    srch = SearchForm()
    if srch.validate_on_submit():
        return redirect(url_for('jobs.search_result', category=srch.category.data, search=srch.search.data, page=page))
    else:
        srch.search.data = search
        srch.category.data = category
        jobs = Job.query.filter(Job.postType == category).filter(
            Job.title.contains(f'{search}')).order_by(Job.timeStamp.desc()).paginate(per_page=2, page=int(page))
        return render_template('job_search.html', title='Search Result', sform=srch, jobs=jobs, c=category, s=search)


@jobs.route('/specific_job/<id>')
@login_required
def specific_job(id):
    job = Job.query.filter_by(id=id).first()
    working = Works.query.filter(Works.jobID == job.id)
    if Works.query.filter(Works.jobID == job.id).filter(Works.userID == current_user.id).first():
        status = True

    else:
        status = False
        for work in working:
            if work.status == 'Not Working Not Read':
                work.status = 'Not Working Read'
            if work.status == "Done Not Read":
                work.status = "Done Read"
    db.session.commit()
    return render_template('specific_job.html', title="Job Info", job=job, status=status, work=working)


@jobs.route('/cancel_apply/<id>/<username>')
@login_required
def cancel_apply(id, username):
    job = Job.query.filter_by(id=id).first()
    user = User.query.filter_by(username=username).first()
    w = Works.query.filter(Works.jobID == job.id).filter(
        Works.userID == user.id).first()
    if w.status == 'Working' or w.status == 'Hiring':
        w.worker.isEmployed = False
    db.session.delete(w)
    db.session.commit()
    flash('Successfully Canceled Request', category='success')
    return redirect(url_for('jobs.specific_job', id=job.id))


@jobs.route('/job_apply/<id>')
@login_required
def job_apply(id):
    w = Works()
    job = Job.query.filter_by(id=id).first()
    user = User.query.filter_by(id=current_user.id).first()
    if Works.query.filter(Works.jobID == job.id).filter(Works.userID == user.id).first():
        flash('You Already Applied for this job!', category='danger')
        return redirect(url_for('jobs.specific_job', id=job.id))
    else:
        w.worked_job = job
        w.worker = current_user
        job.workers.append(w)
        db.session.add(w)
        db.session.commit()
        flash('Applied Successfully please wait for approval!', category='success')
        return redirect(url_for('jobs.specific_job', id=job.id))


@jobs.route('/accept_seeker/<username>/<id>')
@login_required
def accept_seeker(username, id):
    job = Job.query.filter_by(id=id).first()
    user = User.query.filter_by(username=username).first()
    if job.postType == 'Seeker':
        if user.isEmployed:
            flash('You are already Employed!', category='danger')
            return redirect(url_for('jobs.specific_job', id=job.id))
        w = Works.query.filter(Works.jobID == job.id).filter(
            Works.userID == user.id).first()
        w.status = 'Hiring'
        job.user.isEmployed = True
        w.isAccepted = True
        db.session.commit()
        flash('Successfully Accepted Job!', category='success')
        return redirect(url_for('jobs.specific_job', id=job.id))
    else:
        if job.user.isEmployed:
            flash('User is already Employed!', category='danger')
            return redirect(url_for('jobs.specific_job', id=job.id))
        w = Works.query.filter(Works.jobID == job.id).filter(
            Works.userID == user.id).first()
        wo = Works.query.filter(Works.jobID == job.id)
        n = 0
        for wor in wo:
            if wor.status == 'Working':
                n = n + 1
        if int(job.maxWorker) == n or int(job.maxWorker) < n:
            flash("Maximum Worker Achieved Can't Accept more worker!", category='danger')
            return redirect(url_for('jobs.specific_job', id=job.id))
        w.status = 'Working'
        user.isEmployed = True
        w.isAccepted = True
        db.session.commit()
        flash('Successfully Accepted User!', category='success')
        return redirect(url_for('jobs.specific_job', id=job.id))


@jobs.route('/job_done/<username>/<id>', methods=['GET', 'POST'])
@login_required
def job_done(username, id):
    form = FeedbackForm()
    job = Job.query.filter(Job.id == id).first()
    user = User.query.filter(User.username == username).first()
    if job.postType == 'Employer':
        current_user.isEmployed = False
    else:
        u = User.query.filter(User.id == job.user.id).first()
        u.isEmployed = False
    if request.method == 'POST' and form.validate_on_submit():
        print(request.form['selected_rating'])
        print(user)
        work = Works.query.filter(Works.jobID == job.id).filter(
            Works.userID == user.id).first()
        work.status = 'Done Not Read'
        work.message = form.message.data
        work.ratings = request.form['selected_rating']
        if work.ratings:
            db.session.commit()
            flash('Success', category='success')
            return redirect(url_for('jobs.specific_job', id=id))
        else:
            flash('Please rate the User.', category='danger')
            form.message.data = work.message
            return redirect(url_for('jobs.job_done', username=username, id=id))
    else:
        return render_template('feedback.html', form=form, job=job, user=user)


@jobs.route('/messages/<page1>/<page2>')
@login_required
def message(page1, page2):
    r = Message.query.filter(Message.toUserID == current_user.id).order_by(

app/users/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from app import db
from flask_login import current_user, login_user, logout_user, login_required
from werkzeug.urls import url_parse
from app.users. utils import save_picture

from app.users.forms import LoginForm, RegistrationForm, EditProfile, EditIMG
from app.models import User, Job, Works


users = Blueprint('users', __name__)


@users.route('/sign_up', methods=['GET', 'POST'])
def sign_up():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User()
        user.username = form.username.data
        user.first_name = form.firstname.data.title()
        user.last_name = form.lastname.data.title()
        user.gender = form.gender.data
        user.email = form.email.data
        user.contact = form.contact_no.data
        user.password = form.password.data
        user.address = form.location.data
        date = form.birthDate.data.split('/')
        year = date.pop()
        date.insert(0, year)
        newDate = ""
        for i in date:
            newDate += i + "-"
        newDate = newDate[:-1]
        user.birthDate = newDate
        db.session.add(user)
        db.session.commit()
        flash('Congratulations, you are now a registered user!', category='success')
        return redirect(url_for('users.sign_in'))
    return render_template('sign_up.html', title='Sign Up', form=form)


@users.route('/sign_in', methods=['POST', 'GET'])
def sign_in():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is None or not user.check_password(form.password.data):
            flash('Invalid Username or Password', category='danger')
            return redirect(url_for('users.sign_in'))
        login_user(user, remember=form.remember_me.data)
        next_page = request.args.get('next')
        if not next_page or url_parse(next_page).netloc != '':
            next_page = url_for(
                'users.home', username=current_user.username, post_page=1, hired_page=1, history_page=1)
        return redirect(next_page)
    return render_template('sign_in.html', title='Sign In', form=form)


@users.route('/sign_out')
def sign_out():
    logout_user()
    return redirect(url_for('users.sign_in'))


@users.route('/edit_profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfile()
    if form.validate_on_submit() and request.method == 'POST':
        current_user.first_name = form.firstname.data
        current_user.last_name = form.lastname.data
        current_user.contact = form.contact_no.data
        current_user.email = form.email.data
        current_user.gender = form.gender.data
        current_user.address = form.location.data
        db.session.commit()
        flash('Successfully Edited Profile.', category='success')
        return redirect(url_for('users.home', username=current_user.username, post_page=1, hired_page=1, history_page=1))
    else:
        form.firstname.data = current_user.first_name
        form.lastname.data = current_user.last_name
        form.gender.data = current_user.gender
        form.email.data = current_user.email
        form.location.data = current_user.address
        form.gender.data = current_user.gender
        form.contact_no.data = current_user.contact
        return render_template('edit_profile.html', title='Edit Profile', form=form)


@users.route('/home/<username>/<post_page>/<hired_page>/<history_page>', methods=['POST', 'GET'])
@login_required
def home(username, post_page, hired_page, history_page):
    form = EditIMG()
    user = User.query.filter_by(username=username).first()
    job_posted = Job.query.filter(Job.userId == user.id).order_by(Job.timeStamp.desc()).paginate(
        per_page=2, page=int(post_page))
    current_age = user.get_age()
    image_file = url_for(
        'static', filename='profile_pics/' + user.image_file)
    if form.validate_on_submit and request.method == 'POST':
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            user.image_file = picture_file
            db.session.commit()
            flash('Changed Profile Picture.', category='success')
        else:
            flash('Failed', category='danger')
        return redirect(url_for('users.home', username=current_user.username, post_page=1, hired_page=1, history_page=1))
    else:
        return render_template('home.html', title='Profile', form=form, image_file=image_file, age=current_age, job_posted=job_posted, user=user,
                               current_post_page=post_page, current_hired_page=hired_page, current_history_page=history_page)


@users.route('/uploadIMG', methods=['POST'])
def uploadIMG():
    image_file = url_for(
        'static', filename='profile_pics/' + current_user.image_file)

app/templates/MainTemplate.html
<!DOCTYPE html>
<html>
<head>
	{% block head %}
	<title>{% block title %}{% endblock %}</title>
	<link href="../static/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link rel="stylesheet" type="text/css" href="../static/css/register.css">
    <link rel="stylesheet" type="text/css" href="../static/css/land_page.css">
	{% endblock %}
	
</head>
<body>
	{% block body %}
	{% endblock %}
	<script src="../static/js/jquery.js"></script>
	<script src="../static/js/bootstrap.min.js"></script>
	{% block scripts %}
	{% endblock %}
</body>
</html>

app/templates/messages.html
{% extends 'base.html' %}


{% block link %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static', filename='css/messages.css')}}">
<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
    crossorigin="anonymous">

{% endblock link %}


{% block page_content %}
{% include 'layout/navbar.html' %}

<div class="container">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    <div class="mt-3 alert alert-{{category}}">
        <button class="close" type="button" data-dismiss="alert">&times;</button>
        {{message}}
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}
</div>
<div class="container">
    <div class="my_container mt-5">
        <ul class="nav justify-content-center nav-pills nav-fill">
            <li class="nav-item">
                <a class="nav-link btn-danger" id="sentBtn" href="#sentBtn">Sent</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="receiveBtn" href="#receiveBtn">Received</a>
            </li>

        </ul>
    </div>
    <div id="sent" class="mt-5">

        {% if s.items.length %}
        <table class="table table-hover">
            <thead class="thead-dark">
                <tr>
                    <th scope="col" style="width:10%">#</th>
                    <th scope="col" style="width:40%">Message</th>
                    <th scope="col" style="width:30%">Job</th>
                    <th scope="col" style="width:20%">TimeStamp</th>
                </tr>
            </thead>
            <tbody>
                {% for message1 in s.items %}
                <tr>
                    <th scope="row">
                        <a href="{{url_for('jobs.specific_message', messageID=message1.id)}}">
                            {{loop.index}}.
                        </a>
                    </th>
                    <th>
                        <a href="{{url_for('jobs.specific_message', messageID=message1.id)}}">
                            {{message1.content|truncate(50, True)}}
                        </a>
                    </th>
                    <th>
                        <a href="{{url_for('jobs.specific_message', messageID=message1.id)}}">
                            {{message1.jobTitle|truncate(30, True)}}
                        </a>
                    </th>
                    <th>
                        <a href="{{url_for('jobs.specific_message', messageID=message1.id)}}">
                            {{message1.timeStamp.now().date()}}
                        </a>
                    </th>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="text-center">
            {% for page_num2 in s.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}

            {% if page_num2 %}
            {% if s.page == page_num2 %}
            <a href="{{url_for('jobs.message', page1=page_num1, page2=page_num2)}}" class="btn btn-info mb-4">{{page_num2}}</a>
            {% else %}
            <a href="{{url_for('jobs.message', page1=page_num1, page2=page_num2)}}" class="btn btn-outline-info mb-4">{{page_num2}}</a>
            {% endif %}
            {% else %}
            ...
            {% endif %}

            {% endfor %}
        </div>
        {% else %}
        <div class="my_container">
            <h1 class="text-center">No Messages Sent !</h1>
        </div>
        {% endif %}
    </div>
    <div id="receive" class="mt-5">

        {% if r.items.length %}
        <table class="table table-hover">
            <thead class="thead-dark">
                <tr>
                    <th scope="col" style="width:10%">#</th>
                    <th scope="col" style="width:40%">Message</th>
                    <th scope="col" style="width:30%">Job</th>
                    <th scope="col" style="width:20%">TimeStamp</th>
                </tr>
            </thead>
            <tbody>
                {% for message2 in r.items %}

                {% if message2.status == 'Not Read' %}
                <tr class="bg-info">
                    {% else %}
                <tr>
                    {% endif %}

                    <th scope="row">
                        <a href="{{url_for('jobs.specific_message', messageID=message2.id)}}">
                            {{loop.index}}.
                        </a>
                    </th>
                    <th>
                        <a href="{{url_for('jobs.specific_message', messageID=message2.id)}}">
                            {{message2.content|truncate(50, True)}}
                        </a>
                    </th>
                    <th>
                        <a href="{{url_for('jobs.specific_message', messageID=message2.id)}}">
                            {{message2.jobTitle|truncate(30, True)}}
                        </a>
                    </th>
                    <th>
                        <a href="{{url_for('jobs.specific_message', messageID=message2.id)}}">
                            {{message2.timeStamp.now().date()}}
                        </a>
                    </th>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <div class="text-center">
            {% for page_num1 in s.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}

            {% if page_num1 %}
            {% if s.page == page_num1 %}
            <a href="{{url_for('jobs.message', page1=page_num1, page2=page_num2)}}" class="btn btn-info mb-4">{{page_num1}}</a>
            {% else %}
            <a href="{{url_for('jobs.message', page1=page_num1, page2=page_num2)}}" class="btn btn-outline-info mb-4">{{page_num1}}</a>
            {% endif %}
            {% else %}
            ...
            {% endif %}

            {% endfor %}
        </div>
        {% else %}
        <div class="my_container">
            <h1 class="text-center">No Messages Received !</h1>
        </div>
        {% endif %}
    </div>
</div>
{% endblock page_content %}


{% block script %}
{{super()}}
<script src="{{url_for('static', filename='js/messages.js')}}"></script>
{% endblock script %}

app/templates/specific_job.html
{% extends 'base.html' %}

{% block link %}
{{super()}}
<link rel="stylesheet" href="{{ url_for('static', filename='css/job_search.css') }}">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt"
    crossorigin="anonymous">
<link rel="stylesheet" href="{{ url_for('static', filename='css/specific_job.css') }}">
{% endblock link %}

{% block page_content %}
{% include 'layout/navbar.html' %}
<div class="container">

    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    <div class="mt-3 alert alert-{{category}}">
        <button class="close" type="button" data-dismiss="alert">&times;</button>
        {{message}}
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}
</div>
<div class="container">
    <br>
    <div class=" my_container">
        <div class="mt-3 mb-5">

            <h3 class="source mt-2 text-right text-primary">
                Job {{job.postType}}
            </h3>
            <h1 class="text-center montserrat sections">{{job.title}}</h1>
            <table class="source table table-sm table-borderless">
                <thead>
                    <tr>
                        <td><strong>Job Type</strong></td>
                        <td>

                            {% if job.jobType == 'FT' %}
                            Full Time
                            {% else %}
                            Part Time
                            {% endif %}

                        </td>
                    </tr>
                </thead>
                <thead>
                    <tr>
                        <td><strong>Job Description</strong></td>
                        <td>{{job.description}}</td>
                    </tr>
                </thead>
                <thead>
                    <tr>
                        <td><strong>Indicated Location</strong></td>
                        <td>{{job.location}}</td>
                    </tr>
                </thead>
                <thead>
                    <tr>
                        <td><strong>Indicated Salary</strong></td>
                        <td>{{job.salary}}</td>
                    </tr>
                </thead>

                {% if job.maxWorker %}

                <thead>
                    <tr>
                        <td><strong>Max Employee</strong></td>
                        <td>
                            {{job.maxWorker}}
                        </td>
                    </tr>
                </thead>
                {% endif %}
            </table>

            {% if job.user != current_user %}

            <p class="source text-right">Posted By: <span class="montserrat"><a href="{{url_for('users.home', username=job.user.username, post_page=1, hired_page=1, history_page=1)}}">{{job.user}}</a></span></p>

            {% endif %}

            {% if current_user != job.user %}
            <a href="{{url_for('jobs.create_message', jobID=job.id, fromUserID=current_user.id, toUserID=job.user.id)}}"
                class="btn btn-success">Message</a>
            {% endif %}


            {% if job.user != current_user%}


            {% if not status %}

            <a href="{{url_for('jobs.job_apply', id=job.id)}}" class="btn btn-primary" id="editBTN">
                {% if job.postType == 'Employer' %}
                Apply
                {% else %}
                Hire
                {% endif %}
            </a>
            {% else %}

            {% for wjob in current_user.worked_jobs %}
            {% if wjob.jobID == job.id and wjob.status == 'Working'%}
            <a href="#" class="btn btn-success disabled">Working On the Job</a>
            {% elif wjob.jobID == job.id and wjob.status == 'Not Working Read'%}
            <a href="#" class="btn btn-success disabled">Pending Request</a>
            {% elif wjob.jobID == job.id and wjob.status == 'Hiring'%}
            <a href="{{url_for('jobs.job_done', username=current_user.username, id=job.id)}}" class="btn btn-success">Work
                is
                Done</a>
            {% endif %}

            {% endfor %}

            <!-- Button trigger modal -->
            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal">
                Cancel
            </button>

            <!-- Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Cancel Request</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            You are about to cancel this job {{job.title}}
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <a href="{{url_for('jobs.cancel_apply', id=job.id, username=current_user.username)}}" class="btn btn-danger">Yes</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}

            {% endif %}
        </div>

        {% if job.user == current_user and (job.worker_count() or job.hiring_count()) %}
        <hr>
        <h3>People
            {% if job.postType == 'Seeker' %}
            You worked with
            {% else %}
            Who Works for You
            {% endif %}
            :</h3>
        <ul class="list-group">
            {% for worker in work %}
            {% if worker.status == 'Hiring' or worker.status == 'Working' %}
            <li class="list-group-item list-group-item-success">



                {{worker.worker}}
                <div style="float: right">

                    {% if job.postType == 'Employer' %}
                    <a href="{{url_for('jobs.job_done', username=worker.worker.username, id=job.id)}}" class="btn btn-sm btn-success">Done</a>
                    {% else %}
                    <a href="#" class="btn btn-sm btn-info disabled">Working On It!</a>
                    {% endif %}

                    <button type="button" class="btn btn-sm btn-danger" data-toggle="modal" data-target="#exampleModal{{worker.worker.id}}">
                        Delete
                    </button>
                </div>
            </li>
            <!-- Button trigger modal -->

            <!-- Modal -->
            <div class="modal fade" id="exampleModal{{worker.worker.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel{{worker.worker.id}}"
                aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel{{worker.worker.id}}">Delete User</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <h3 class="text-center source">You Are About to Delete User {{worker.worker.first_name}}.</h3>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-sm btn-secondary" data-dismiss="modal">Close</button>
                            <a href="{{url_for('jobs.cancel_apply', id=job.id, username=worker.worker.username)}}"
                                class="btn btn-sm btn-danger">Yes</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
            {% endfor %}
        </ul>
        {% endif %}
        <hr>

        {% if job.user == current_user and job.applying_count() %}
        <h3>People
            {% if job.postType == 'Seeker' %}
            Hiring You
            {% else %}
            Applying
            {% endif %}
            :</h3>
        <ul class="list-group">
            {% for worker in work if worker.status == 'Not Working Read' %}
            <li class="list-group-item list-group-item-success">
                <a href="{{url_for('users.home', username=worker.worker.username, post_page=1, hired_page=1, history_page=1)}}">
                    {{worker.worker}}
                </a>
                <div style="float: right">
                    <a href="{{url_for('jobs.accept_seeker', username=worker.worker.username, id=job.id)}}" class="btn btn-sm btn-success">Accept</a>
                    <a href="{{url_for('jobs.cancel_apply', id=job.id, username=worker.worker.username)}}" class="btn btn-sm btn-danger">Decline</a>
                </div>
            </li>
            {% endfor %}
        </ul>
        {% endif %}

    </div>
</div>
{% endblock page_content %}

app/templates/test.html
{{message}}
{% for m in message %}
{{m[0]}}
{% endfor %}